services:
  redis:
    image: "redis:alpine"

  postgres:
    image: "postgres:15"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - ./.data:/var/lib/postgresql/data

  web:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    env_file:
      - .envs/development.env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./app/static:/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

  celery:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: docker/worker/Dockerfile
    env_file:
      - .envs/development.env
    volumes:
      - .:/code
    depends_on:
      - redis
      - postgres
