# Generated by Django 5.1.1 on 2024-10-25 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_remove_userhabit_habit_logs_habitlog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='difficulty_level',
            field=models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userhabit',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned')], max_length=50),
        ),
    ]
