# Generated by Django 5.1.1 on 2024-10-26 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_remove_userhabit_notifications_enabled'),
        ('milestones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhabit',
            name='next_skill_unlock',
        ),
        migrations.AddField(
            model_name='userhabit',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RemoveField(
            model_name='habit',
            name='milestones',
        ),
        migrations.AddField(
            model_name='habit',
            name='milestones',
            field=models.ManyToManyField(related_name='habits', to='milestones.milestone'),
        ),
    ]
